language: node_js
node_js:
  - 8
  - 10
  - 12
script:
  - npm run build
  - npm test

jobs:
  include:
    - stage: deploy
      node_js: 10
      script:
        - npm run doc
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs
        on:
          branch: master
      before_deploy:
        - touch docs/.nojekyll
