language: node_js
node_js:
  - 12
  - 10
  - 8
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
  - npm run doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
before_deploy:
  - touch docs/.nojekyll
